version: '3.9'

services:

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - "4444:5432"
    expose:
      - 4444
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data7
    environment:
      - POSTGRES_DB=AlkhaierDb
      - POSTGRES_USER=khaier
      - POSTGRES_PASSWORD=khaier